# Generated by Django 5.0.6 on 2024-05-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="check_in_time",
            field=models.TimeField(default="14:00:00"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="check_out_time",
            field=models.TimeField(default="12:00:00"),
        ),
    ]
