# Generated by Django 5.0.6 on 2024-05-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_hotel_check_in_time_hotel_check_out_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
